// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StabilityPlatForm.HMProject.DataAccessLayer.DatabaseOperations;

#nullable disable

namespace StabilityPlatForm.HMProject.DataAccessLayer.Migrations
{
    [DbContext(typeof(HMDatabaseContext))]
    partial class HMDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StabilityPlatForm.HMProject.DataAccessLayer.DatabaseOperations.IvCurveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SweepDirection")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TimeHours")
                        .HasColumnType("double");

                    b.Property<string>("VoltageDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IvCurves");
                });

            modelBuilder.Entity("StabilityPlatForm.HMProject.DataAccessLayer.DatabaseOperations.StabilityResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("FF")
                        .HasColumnType("double");

                    b.Property<double>("Jsc")
                        .HasColumnType("double");

                    b.Property<double>("Pmax")
                        .HasColumnType("double");

                    b.Property<double>("Rseries")
                        .HasColumnType("double");

                    b.Property<double>("Rshunt")
                        .HasColumnType("double");

                    b.Property<bool>("SweepDirection")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<double>("TimeHours")
                        .HasColumnType("double");

                    b.Property<double>("Voc")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("StabilityResults");
                });
#pragma warning restore 612, 618
        }
    }
}
